// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	transactionmodel "github.com/amnestia/xyz-multifinance/internal/domain/model/transaction"
)

// TransactionRepository is an autogenerated mock type for the TransactionRepository type
type TransactionRepository struct {
	mock.Mock
}

// Commit provides a mock function with given fields: tx
func (_m *TransactionRepository) Commit(tx *sqlx.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateNewPayment provides a mock function with given fields: ctx, tx, req
func (_m *TransactionRepository) CreateNewPayment(ctx context.Context, tx *sqlx.Tx, req *transactionmodel.Payment) (int64, error) {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewPayment")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *transactionmodel.Payment) (int64, error)); ok {
		return rf(ctx, tx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *transactionmodel.Payment) int64); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *transactionmodel.Payment) error); ok {
		r1 = rf(ctx, tx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateNewPaymentInstallment provides a mock function with given fields: ctx, tx, req
func (_m *TransactionRepository) CreateNewPaymentInstallment(ctx context.Context, tx *sqlx.Tx, req *transactionmodel.PaymentInstallment) (int64, error) {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewPaymentInstallment")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *transactionmodel.PaymentInstallment) (int64, error)); ok {
		return rf(ctx, tx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *transactionmodel.PaymentInstallment) int64); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *transactionmodel.PaymentInstallment) error); ok {
		r1 = rf(ctx, tx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateNewTransaction provides a mock function with given fields: ctx, tx, req
func (_m *TransactionRepository) CreateNewTransaction(ctx context.Context, tx *sqlx.Tx, req *transactionmodel.Transaction) (int64, error) {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewTransaction")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *transactionmodel.Transaction) (int64, error)); ok {
		return rf(ctx, tx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *transactionmodel.Transaction) int64); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, *transactionmodel.Transaction) error); ok {
		r1 = rf(ctx, tx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLimit provides a mock function with given fields: ctx, req
func (_m *TransactionRepository) GetLimit(ctx context.Context, req transactionmodel.LookupPayload) (transactionmodel.Limit, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetLimit")
	}

	var r0 transactionmodel.Limit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, transactionmodel.LookupPayload) (transactionmodel.Limit, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, transactionmodel.LookupPayload) transactionmodel.Limit); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(transactionmodel.Limit)
	}

	if rf, ok := ret.Get(1).(func(context.Context, transactionmodel.LookupPayload) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOngoingPayment provides a mock function with given fields: ctx, req
func (_m *TransactionRepository) GetOngoingPayment(ctx context.Context, req transactionmodel.LookupPayload) ([]transactionmodel.Payment, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetOngoingPayment")
	}

	var r0 []transactionmodel.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, transactionmodel.LookupPayload) ([]transactionmodel.Payment, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, transactionmodel.LookupPayload) []transactionmodel.Payment); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transactionmodel.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, transactionmodel.LookupPayload) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOngoingPaymentInstallment provides a mock function with given fields: ctx, req
func (_m *TransactionRepository) GetOngoingPaymentInstallment(ctx context.Context, req transactionmodel.LookupPayload) ([]transactionmodel.PaymentInstallment, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetOngoingPaymentInstallment")
	}

	var r0 []transactionmodel.PaymentInstallment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, transactionmodel.LookupPayload) ([]transactionmodel.PaymentInstallment, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, transactionmodel.LookupPayload) []transactionmodel.PaymentInstallment); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]transactionmodel.PaymentInstallment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, transactionmodel.LookupPayload) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransaction provides a mock function with given fields: ctx
func (_m *TransactionRepository) NewTransaction(ctx context.Context) (*sqlx.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewTransaction")
	}

	var r0 *sqlx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*sqlx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *sqlx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RollbackOnError provides a mock function with given fields: tx, err
func (_m *TransactionRepository) RollbackOnError(tx *sqlx.Tx, err error) error {
	ret := _m.Called(tx, err)

	if len(ret) == 0 {
		panic("no return value specified for RollbackOnError")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sqlx.Tx, error) error); ok {
		r0 = rf(tx, err)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactionRepository creates a new instance of TransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionRepository {
	mock := &TransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
